name: eu-west-1
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'prod/eu-west-1/**'
      - '.github/workflows/eu-west-1.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'prod/eu-west-1/**'
      - '.github/workflows/eu-west-1.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  plan-prod:
    runs-on: ubuntu-latest
    environment: plan-prod
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: plan
        run: |
          echo "plan"
        shell: bash

      - name: Sanitize
        if: github.event_name == 'pull_request'
        run: |
          echo "Sanitize"
        shell: bash
        
      - name: CIDR CHECK
        if: github.event_name == 'pull_request'
        run: |
          echo "check"
        shell: bash

  apply-prod:
    runs-on: ubuntu-latest
    environment: apply-prod
    needs: plan-prod
    if: github.event_name != 'pull_request'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: apply
        run: |
          echo "apply"
        shell: bash
