# terraform-pr.yml
name: Terraform PR Plan
on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install Checkov
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3-pip && \
          pip3 install checkov
        shell: bash

      - name: run checkov
        id: checkov
        run: |
          checkov -d . --download-external-modules true --skip-path variables --skip-path backends --skip-path ./.github/workflows --skip-check CKV_TF_1 --skip-check CKV_AWS_144 --skip-check CKV2_AWS_62 --skip-check CKV2_AWS_61 --skip-check CKV2_AWS_39 --skip-check CKV2_AWS_38 --skip-check CKV_AWS_124
        shell: bash
        
  plan-dev:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      terraform_action: plan
      environment: dev
      aws_role: arn:aws:iam::123456789012:role/dummy-role

  plan-stage:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      terraform_action: plan
      environment: stage
      aws_role: arn:aws:iam::123456789012:role/dummy-role

  plan-prod:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      terraform_action: plan
      environment: prod
      aws_role: arn:aws:iam::123456789012:role/dummy-role
